[licenses]
default = "deny"
allow = ["MIT"]
unlicensed = "warn"

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
